secondproject/movieapp/urls.py
# from django.conf import settings
# from django.conf.urls.static import static
from django.urls import path, include
from . import views
app_name='movieapp'
urlpatterns = [
    path('',views.index,name="index"),
    path('movie/<int:movie_id>/',views.list,name="list"),
    path('add/',views.add,name="add"),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')

]

secondproject/secondproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

secondproject/movieapp/models.py
from django.db import models

# Create your models here.
class movies(models.Model):
    Movie_Name=models.CharField(max_length=100)
    Movie_description=models.TextField()
    Movie_Year=models.IntegerField()
    Movie_img=models.ImageField(upload_to='pic')
    def __str__(self):
        return self.Movie_Name

secondproject/movieapp/forms.py
from django import forms
from .models import movies
class Form(forms.ModelForm):
    class Meta:
        model=movies
        fields=['Movie_Name','Movie_description','Movie_Year','Movie_img']

secondproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template import context
from . models import movies
from .forms import Form
# Create your views here.
def index(request):
    Movie=movies.objects.all()
    context={
        'movies':Movie
    }
    return render(request,"index.html",context)
def list(request,movie_id):
    Movie=movies.objects.get(id=movie_id)
    return render(request,"list.html",{'movie':Movie})
def add(request):
    if request.method=='POST':
        Movie_Name = request.POST.get('Movie_Name','')
        Movie_description = request.POST.get('Movie_description','')
        Movie_Year = request.POST.get('Movie_Year','')
        Movie_img = request.FILES['Movie_img']
        Movie = movies(Movie_Name=Movie_Name,Movie_description=Movie_description,Movie_Year=Movie_Year,Movie_img=Movie_img)
        Movie.save()
    return render(request,"add.html")
def update(request,id):
    movie=movies.objects.get(id=id)
    form=Form(request.POST or None,request.FILES,instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,"edit.html",{'form':form,'movie':movie})
def delete(request,id):
    if request.method == 'POST':
        movie = movies.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')



# Movie = movies(Movie_Name=name,Movie_description=description,Movie_Year=year,Movie_Img=img)

secondproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
<input type="text" name="Movie_Name" placeholder="Enter the Movie_Name"><br>
  <input type="text" name="Movie_description" placeholder="Enter the description of Movie"><br>
  <input type="text" name="Movie_Year" placeholder="Enter the Year Movie"><br>
  <input type="file" name="Movie_img"><br>
  <input type="submit">
</form>
{% endblock %}

secondproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar navbar-Light bg-dark">
    <a class="navbar-brand" href="#">  Movie Buzz </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

secondproject/templates/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  Do you want to delete this movie?
  <input type="submit">
</form>
</body>
</html>

secondproject/templates/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

secondproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container" >
    <div class="row">
        {% for i in movies %}
        <div class="col-md-4">
        <div class="card" style="width: 18rem;margin-bottom:50px">
  <img src="{{i.Movie_img.url}}" alt="Card image cap"  width="250" height="250" >
  <div class="card-body">
    <h5 class="card-title">{{i.Movie_Name}}</h5>
    <p class="card-text" style=" width:200px;height:200px;">{{i.Movie_description}}</p>
    <a href="{% url 'movieapp:list' i.id %}" class="btn btn-primary">View on Movie Detail</a>
  </div>
</div>
    </div>
    {% endfor %}
</div>
</div>
{% endblock %}
<!--<img src="" >-->
<!--<a href=""><br>-->
<!--&ndash;&gt;{{i.Movie_Year}}<br>-->
<!--<img src="{{i.movie_img.url}}" width="50" height="50">-->

secondproject/templates/list.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img  style="margin-bottom:50px;height:400px;width:500px;" src="{{movie.Movie_img.url}}">
        </div>
        <div class="col-md-6">
            <h6>{{movie.Movie_Name}}</h6><br>
            <h6>{{movie.Movie_description}}</h6><br>
            <h6>{{movie.Movie_Year}}</h6><br>
            <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">delete</a>
        </div>
    </div>
</div>
{% endblock %}
<!--<img src="{{movie.Movie_Img.url}}" width="100" height="100">-->